run:
  timeout: 5m
  include:
    - internal
    - storage
    - main.go
  skip-dirs:
    - docs/swagger
    - openapi
  skip-files:
    - ".*_gen.go"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - revive
    - ineffassign

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    # rules:
    #   - name: var-naming
    #     arguments:
    #       initialisms:
    #         - ID
    #         - API
    #         - HTTP

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  format: colored-line-number
