run:
  timeout: 5m
  include:
    - internal
    - storage
    - main.go
  skip-dirs:
    - docs/swagger   # Swagger生成物を除外
    - openapi       # OpenAPI生成物を除外
  skip-files:
    - ".*_gen.go"   # 生成コードを除外（任意）

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - deadcode
    - gofmt
    - goimports
    - revive
    - ineffassign

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: var-naming
        arguments:
          allow-leading-underscore: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rule
