name: reviewdog

on:
  pull_request:

jobs:
  lint:
    name: Run golangci-lint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3

      - name: Run golangci-lint
        id: lint
        run: |
          golangci-lint run --out-format=line-number > result.log || true
          cat result.log

      - name: Run reviewdog
        uses: reviewdog/reviewdog@v0.14.0
        with:
          name: golangci-lint
          reporter: github-pr-review
          filter-mode: diff_context
          fail-on-error: false
          level: warning
          output: result.log